version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: expo-image-picker
    versions:
    - 10.0.0
    - 10.1.3
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: react-native-screens
    versions:
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: expo-status-bar
    versions:
    - 1.0.3
  - dependency-name: expo-font
    versions:
    - 9.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
